-- Private order feedback with public aggregate ratings.
-- Private messages and admin replies must never be exposed publicly.

create table if not exists public.order_feedback (
  id bigint generated by default as identity primary key,

  order_id bigint not null unique
    references public.orders(id) on delete cascade,

  rating smallint not null
    check (rating between 1 and 5),

  private_message text
    check (
      private_message is null
      or char_length(btrim(private_message)) between 1 and 2000
    ),

  -- The rating contributes to the public aggregate in all cases.
  -- A customer's first name is public only with explicit consent.
  public_name_consent boolean not null default false,

  public_display_name text
    check (
      public_display_name is null
      or char_length(btrim(public_display_name)) between 1 and 80
    ),

  public_name_consent_at timestamptz,

  admin_seen_at timestamptz,

  private_message_removed_at timestamptz,

  private_message_removed_by uuid
    references auth.users(id) on delete set null,

  admin_reply text
    check (
      admin_reply is null
      or char_length(btrim(admin_reply)) between 1 and 2000
    ),

  admin_replied_at timestamptz,

  admin_replied_by uuid
    references auth.users(id) on delete set null,

  restaurant_notification_email_claimed_at timestamptz,
  restaurant_notification_email_sent_at timestamptz,
  restaurant_notification_email_error text,

  customer_reply_email_claimed_at timestamptz,
  customer_reply_email_sent_at timestamptz,
  customer_reply_email_error text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (
    (
      public_name_consent = false
      and public_display_name is null
    )
    or
    (
      public_name_consent = true
      and public_display_name is not null
      and public_name_consent_at is not null
       )
  ),
  constraint order_feedback_removed_message_check
  check (
    (
      private_message_removed_at is null
      and private_message_removed_by is null
    )
    or
    (
      private_message_removed_at is not null
      and private_message is null
    )
  ),

  check (
    (
      admin_reply is null
      and admin_replied_at is null
      and admin_replied_by is null
    )
    or
    (
      admin_reply is not null
      and admin_replied_at is not null
    )
  )
);

create index if not exists order_feedback_created_at_idx
  on public.order_feedback (created_at desc);

create index if not exists order_feedback_unseen_idx
  on public.order_feedback (created_at desc)
  where admin_seen_at is null;

create index if not exists order_feedback_public_names_idx
  on public.order_feedback (created_at desc)
  where public_name_consent = true;

alter table public.order_feedback enable row level security;

-- No anon/authenticated policies are intentionally created.
-- Customer-token and admin authorization are verified by server-side APIs.
-- The Supabase service role is the only database access path.

alter table public.orders
  add column if not exists feedback_invitation_email_claimed_at timestamptz,
  add column if not exists feedback_invitation_email_sent_at timestamptz,
  add column if not exists feedback_invitation_email_error text;

