create table if not exists public.store_service_hours (
  id bigint generated by default as identity primary key,

  -- 1 = Monday ... 7 = Sunday
  day_of_week smallint not null
    check (day_of_week between 1 and 7),

  service_type text not null
    check (service_type in ('pickup', 'delivery')),

  is_enabled boolean not null default true,

  preorder_start time without time zone not null default '10:00',
  opening_time time without time zone not null default '15:00',
  first_scheduled_time time without time zone not null default '15:30',
  last_scheduled_time time without time zone not null default '20:30',
  closing_time time without time zone not null default '21:00',

  slot_interval_minutes smallint not null default 15
    check (slot_interval_minutes between 5 and 120),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint store_service_hours_day_service_unique
    unique (day_of_week, service_type),

  constraint store_service_hours_time_order_check
    check (
      preorder_start <= opening_time
      and opening_time <= first_scheduled_time
      and first_scheduled_time <= last_scheduled_time
      and last_scheduled_time <= closing_time
    )
);

alter table public.store_service_hours
enable row level security;

insert into public.store_service_hours (
  day_of_week,
  service_type,
  is_enabled,
  preorder_start,
  opening_time,
  first_scheduled_time,
  last_scheduled_time,
  closing_time,
  slot_interval_minutes
)
select
  day_number,
  service.service_type,
  true,
  '10:00'::time,
  '15:00'::time,
  '15:30'::time,
  '20:30'::time,
  '21:00'::time,
  15
from generate_series(1, 7) as day_number
cross join (
  values
    ('pickup'),
    ('delivery')
) as service(service_type)
on conflict (day_of_week, service_type) do nothing;
