-- Durable, server-only operational alerts for payment and order failures.
-- Alert context must never contain secrets or customer personal data.

create table if not exists public.operational_alerts (
  id bigint generated by default as identity primary key,

  dedupe_key text not null unique
    check (char_length(dedupe_key) between 1 and 200),

  category text not null
    check (char_length(category) between 1 and 80),

  severity text not null
    check (severity in ('warning', 'critical')),

  summary text not null
    check (char_length(summary) between 1 and 500),

  checkout_session_id uuid
    references public.checkout_sessions(id) on delete set null,

  -- Kept without a foreign key because historical orders may use a
  -- different integer width across environments.
  order_id bigint,

  context jsonb not null default '{}'::jsonb
    check (jsonb_typeof(context) = 'object'),

  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  notification_claimed_at timestamptz,
  notified_at timestamptz,
  notification_error text,

  resolved_at timestamptz
);

create index if not exists operational_alerts_open_severity_idx
  on public.operational_alerts (severity, last_seen_at desc)
  where resolved_at is null;

create index if not exists operational_alerts_checkout_session_idx
  on public.operational_alerts (checkout_session_id)
  where checkout_session_id is not null;

create index if not exists operational_alerts_order_idx
  on public.operational_alerts (order_id)
  where order_id is not null;

alter table public.operational_alerts enable row level security;

-- No anon/authenticated policies are intentionally created.
-- Access is server-side only through the Supabase service role.

alter table public.orders
  add column if not exists restaurant_notification_email_claimed_at timestamptz,
  add column if not exists restaurant_notification_email_sent_at timestamptz;